#!/usr/bin/env python3
"""Regenerate launch/data.js from the market inventory snapshot.

Run from anywhere:  python3 launch/build_data.py
Reads  : ../data/outbid-market-inventory.csv   (bot-maintained, refreshed daily)
         entries.json                          (your paid slots — hand edited or exported from the board)
Writes : data.js  (window.DATA = {...})

No third-party packages. Python 3.9+.
"""
from __future__ import annotations

import csv
import json
import re
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
INVENTORY = HERE.parent / "data" / "outbid-market-inventory.csv"
ENTRIES = HERE / "entries.json"
OUT = HERE / "data.js"

MAX_SEED_ROWS = 80          # rows embedded in the free reference table
MIN_CLAIMED_USD = 1.0       # skip obviously empty boards in the reference table


def money(raw: str) -> float:
    """'$1,505.14' -> 1505.14 ; '' / '0.08 SOL' -> 0.0 (non-USD is ignored here)."""
    s = (raw or "").strip()
    if not s or not s.startswith("$"):
        return 0.0
    m = re.search(r"[\d,]+(?:\.\d+)?", s)
    if not m:
        return 0.0
    try:
        return float(m.group(0).replace(",", ""))
    except ValueError:
        return 0.0


def slug(host: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", host.lower()).strip("-") or "site"


def main() -> int:
    if not INVENTORY.exists():
        raise SystemExit(f"missing inventory: {INVENTORY} (run the daily bot, or check the path)")

    rows = list(csv.DictReader(INVENTORY.open(encoding="utf-8")))
    seed, seen = [], set()
    for r in rows:
        host = (r.get("host") or "").strip()
        claimed = money(r.get("claimed_taken"))
        if not host or host in seen or claimed < MIN_CLAIMED_USD:
            continue
        seen.add(host)
        seed.append(
            {
                "id": slug(host),
                "host": host,
                "name": (r.get("name") or host).strip(),
                "url": (r.get("url") or f"https://{host}").strip(),
                "category": (r.get("category") or "").strip(),
                "tagline": (r.get("tagline") or "").strip(),
                "claimedUsd": round(claimed, 2),
                "bidders": (r.get("bidders") or "").strip(),
                "rail": (r.get("payment_rail") or "").strip(),
                "evidence": (r.get("evidence") or "").strip(),
            }
        )
    seed.sort(key=lambda d: -d["claimedUsd"])
    seed = seed[:MAX_SEED_ROWS]

    entries = {"slots": []}
    if ENTRIES.exists():
        try:
            loaded = json.loads(ENTRIES.read_text(encoding="utf-8") or '{"slots":[]}')
            if isinstance(loaded, dict) and isinstance(loaded.get("slots"), list):
                entries = loaded
        except json.JSONDecodeError as exc:
            print(f"warning: entries.json is not valid JSON ({exc}) — publishing with an empty paid board")

    data = {
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "outoutbid.lol directory (CC BY 4.0) via data/outbid-market-inventory.csv",
        "inventoryRows": len(rows),
        "measuredRows": len(seen),
        "boardTotalUsd": round(sum(s["totalPaid"] for s in entries["slots"]), 2),
        "entries": entries,
        "seed": seed,
    }

    body = "/* Generated by launch/build_data.py — do not hand edit. */\nwindow.DATA = "
    body += json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    body += ";\n"
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT.relative_to(HERE.parent)} — {len(seed)} reference rows, {len(entries['slots'])} paid slot(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
